# Generated by Django 4.2.9 on 2024-10-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountiriesVisited',
            new_name='CountriesVisited',
        ),
        migrations.AlterModelOptions(
            name='countriesvisited',
            options={'verbose_name': 'Country Visited', 'verbose_name_plural': 'Countries Visited'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
